NVCC = /usr/local/cuda/bin/nvcc
NVCC_FLAGS = -g -G -Xcompiler -Wall

all: lab8.exe
lab8.exe: lab8_init.o lab8.o
        $(NVCC) $^ -o $@

lab8_init.o: lab8_init.cpp lab8.h
        $(NVCC) $(NVCC_FLAGS) -c $< -o $@

lab8.o: lab8.cu lab8.h
        $(NVCC) $(NVCC_FLAGS) -c $< -o $@